
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CLANG TRUE CACHE INTERNAL "")

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/clang.exe")
set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/clang++.exe")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/bin/x86_64-unknown-linux-gnu-ar.exe")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/bin/x86_64-unknown-linux-gnu-ranlib.exe")

set(flags "-target x86_64-unknown-linux-gnu \"-B${CMAKE_CURRENT_LIST_DIR}/usr/lib64\"")
set(flags "${flags} --sysroot \"${CMAKE_CURRENT_LIST_DIR}\"")
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} ${flags} -D_ISOC99_SOURCE")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} ${flags}")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
